# Tensors 
Tensors are a data strcuture that are similar to matrices. In pytorch we use tensors to encode  the inputs and outputs of a model, as well as the models parameters . 


Tensors are similar to Numpys ndarrays except that tensors can run on GPUs.Tenssors and NumPy arrays can often share the same underyling memory, eliminating the need to copy data. Tensors are also optimized for automatic differentiation. If you are family with ndarrays, you will be right at home with the Tensor API,

In [1]:
import torch 
import numpy as np

## Initializing a Tensor 
Tensors can be initizalized in various ways. 
### Directly from data 
Tensors can be created directly from data. The data type is automatically infrerred 


In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

### From a Numpy array
Tensors can e created from NumPy arrays 




In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

### From another tensor 
The new tensor retains the properties of the argument tensor unless explicitly overridden 

In [5]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.9296, 0.7413],
        [0.7353, 0.5642]]) 



### With random or constant values 
Shape is a tuple of tensor dimensions. In the functions below it, it determines the dimensionality of the output tensor 


In [6]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.1963, 0.8047, 0.6711],
        [0.9783, 0.2881, 0.5366]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



### Attributes of a Tensor 
Tensor attributes descripe their shape, datatypes, and the device on wich they are stored 


In [7]:
tensor = torch.rand(3,4)
print(f"Shape of tensor:{tensor.shape}")
print(f"Datatype of tensor:{tensor.dtype}")
print(f"Device tensor is stores on :{tensor.device}")


Shape of tensor:torch.Size([3, 4])
Datatype of tensor:torch.float32
Device tensor is stores on :cpu


### Operations on Tensors 
By default tensors are created on the CPU. We need to explicitly move tensors to the GPU using .to method 

In [8]:
# We move our tensor to the GPU if avaiable 
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

### Standard numpy like indexing and slicing 


In [9]:
tensor = torch.ones(4,4)
print('First row:',tensor[0])
print('First column', tensor[:,0])
print('Last column',tensor[...,-1])
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column tensor([1., 1., 1., 1.])
Last column tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### Joining tensors 
You can use torch.cat to concatenate a sequence of tensors along a given dimension

In [10]:
t1 = torch.cat([tensor, tensor, tensor],dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


### Arithemtic operations 

In [11]:
# This computes the matrix multiplication between two tensors 
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(tensor)
torch.matmul(tensor,tensor.T,out=y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [13]:
# This computes the element wise product 
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor,tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

### Single element tesors 
If you have a one element tensor, for example by aggregating all values of a tensor into one value you cn convert it to a python numerical value using item()

In [14]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item,type(agg_item))

12.0 <class 'float'>


### In place operations 
Operations that score the results into the operand are called in place. They are denoted by a _ siffix. 

In [15]:
print(tensor,'\n')
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


## Bridge with Numpy 
Tenser on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other 
### Tensor to NumPy array


In [16]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n:{n}")

t: tensor([1., 1., 1., 1., 1.])
n:[1. 1. 1. 1. 1.]


A change in the tensor reflects in the NumPy array


In [17]:
t.add_(1)
print(f"t: {t}")
print(f"n {n}")

t: tensor([2., 2., 2., 2., 2.])
n [2. 2. 2. 2. 2.]


### NumPy array to Tensor 


In [19]:
n = np.ones(5)
t = torch.from_numpy(n)


Changes in the NumPy array reflects in the tensor 

In [20]:
np.add(n,1,out=n)
print(f"t:{t}")
print(f"n:{n}")


t:tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n:[2. 2. 2. 2. 2.]
